// Poster URL mappings for popular movies
// Using real movie poster URLs from TMDB CDN and other reliable sources

export const posterMapping: Record<string, string> = {
  // Hollywood
  'inception': 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
  'interstellar': 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'titanic': 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
  'avatar': 'https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqoKEC8IJf.jpg',
  'avengers-endgame': 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
  'avengers-infinity-war': 'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
  'the-dark-knight': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'the-shawshank-redemption': 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
  'the-godfather': 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'pulp-fiction': 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
  'forrest-gump': 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
  'the-matrix': 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
  'gladiator': 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
  'joker': 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
  'spider-man-no-way-home': 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
  'top-gun-maverick': 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
  'parasite': 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'dune': 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
  'oppenheimer': 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  'barbie': 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
  'the-lion-king': 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
  'black-panther': 'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
  'jurassic-park': 'https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg',
  'star-wars-a-new-hope': 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
  'the-lord-of-the-rings-fellowship': 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
  'harry-potter-sorcerers-stone': 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
  'back-to-the-future': 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
  'the-social-network': 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
  'whiplash': 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
  'la-la-land': 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
  'eternal-sunshine': 'https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
  'fight-club': 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
  'no-country-for-old-men': 'https://image.tmdb.org/t/p/w500/bj1v6YKF8yHqA489VFfnQvOJpnc.jpg',
  'twelve-angry-men': 'https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'schindlers-list': 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'the-departed': 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
  'good-will-hunting': 'https://image.tmdb.org/t/p/w500/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg',
  'shutter-island': 'https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg',
  'django-unchained': 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg',
  'mad-max-fury-road': 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
  'blade-runner-2049': 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
  'wonder-woman': 'https://image.tmdb.org/t/p/w500/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg',
  'get-out': 'https://image.tmdb.org/t/p/w500/tFXcEccSgONPizH4xqOzEXT06gO.jpg',
  'gravity': 'https://image.tmdb.org/t/p/w500/uAzx06N7TMTYLLmL2etXH7TYWlJ.jpg',
  'coco': 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
  'toy-story-3': 'https://image.tmdb.org/t/p/w500/AbbXspMOwdvwWZgVN0nabZq03Ec.jpg',
  'up': 'https://image.tmdb.org/t/p/w500/vhJ2O6Q7DtJjj0BM4Kl6n3AZxbJ.jpg',
  'finding-nemo': 'https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg',
  'ratatouille': 'https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKw28bJKs7lzqzj.jpg',
  'inside-out': 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
  'wall-e': 'https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg',
  'the-grand-budapest-hotel': 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
  'her': 'https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg',
  'arrival': 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
  'moonlight': 'https://image.tmdb.org/t/p/w500/4911T5FbJ9eD2Faz5Z8L0UD5GPn.jpg',
  'everything-everywhere-all-at-once': 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
  
  // Bollywood
  '3-idiots': 'https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw bekannte1.jpg',
  'dangal': 'https://image.tmdb.org/t/p/w500/lNkJSsYdCO48uNZw1jrPaJUIScN.jpg',
  'pk': 'https://image.tmdb.org/t/p/w500/6xsh1vEPWHyuRlFjPGW3DTHThTX.jpg',
  'baahubali-the-beginning': 'https://image.tmdb.org/t/p/w500/fP8UOceVPWglowHJa6WMXeIoUhj.jpg',
  'baahubali-2': 'https://image.tmdb.org/t/p/w500/w72wAZhhjIKuHLBGnoqOzZfVRXs.jpg',
  'rrr': 'https://image.tmdb.org/t/p/w500/wE0I6efAW4cDDmZQWtwZMOW44EJ.jpg',
  'pathaan': 'https://image.tmdb.org/t/p/w500/qCRP7vOFd5kJeI5l6Q6lPYRJWzz.jpg',
  'lagaan': 'https://image.tmdb.org/t/p/w500/lGbkZERAiVHOg02FpCTMKmWrNR8.jpg',
  'taare-zameen-par': 'https://image.tmdb.org/t/p/w500/or0JTp9RbC6RbGGJwm0Ql4GY8Uu.jpg',
  'gully-boy': 'https://image.tmdb.org/t/p/w500/asa4bH2sPDx53sVJqhDrHyYxOLd.jpg',
  'andhadhun': 'https://image.tmdb.org/t/p/w500/xiY17VN7CYSXNc5hXG1jFuUqxJa.jpg',
  'dilwale-dulhania-le-jayenge': 'https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'sholay': 'https://image.tmdb.org/t/p/w500/4VR1AsKFCjXOXOYODt3f6aLh3Gk.jpg',
  'kgf-chapter-2': 'https://image.tmdb.org/t/p/w500/nEJcWedmKHutOxNNd7xLMXePrBf.jpg',
  'kabir-singh': 'https://image.tmdb.org/t/p/w500/dHofSNZlIJoyywVeXoUcKDRO1zq.jpg',
  'zindagi-na-milegi-dobara': 'https://image.tmdb.org/t/p/w500/y8JCXQOqOwqEXO3j6whOiDkGlQH.jpg',
  'chennai-express': 'https://image.tmdb.org/t/p/w500/4jbJhzQ63SQwkAWMJG3IbTLCdpW.jpg',
  'war': 'https://image.tmdb.org/t/p/w500/2jK7s8vkiJUHHmE40hmpWN44rCJ.jpg',
  'padmaavat': 'https://image.tmdb.org/t/p/w500/lggCREXJwcRz8SbbPYBBSwOEeUo.jpg',
  'article-15': 'https://image.tmdb.org/t/p/w500/uPPCpVSpOmHznYBql5lNUKGZhRA.jpg',
  'rockstar': 'https://image.tmdb.org/t/p/w500/zY1esAE2EkOa4QTAj2p2kqJEPBU.jpg',
  'mughal-e-azam': 'https://image.tmdb.org/t/p/w500/c17gPMlNJwWMLDQWwyBOdADNn8C.jpg',
  'mother-india': 'https://image.tmdb.org/t/p/w500/aI9kbFuDvWXZWphxfSzBHCQXLMt.jpg',
  'swades': 'https://image.tmdb.org/t/p/w500/tR3sIh4VhlQGkPP2KqEsbuWmqc7.jpg',
  'rang-de-basanti': 'https://image.tmdb.org/t/p/w500/fhH0JrWYg33OlV0xXvv54QnzkzX.jpg',
  'gangs-of-wasseypur': 'https://image.tmdb.org/t/p/w500/5Ir88BPsVNw9rNj2UIpJOmQGfvL.jpg',
  'queen': 'https://image.tmdb.org/t/p/w500/9hRzRCg7u6m1mIZx5Kz1hgzhdQL.jpg',
  'pink': 'https://image.tmdb.org/t/p/w500/5qDp6UgPQKv5aqwMuGjZLtL2P2w.jpg',
  'barfi': 'https://image.tmdb.org/t/p/w500/sqOMTqwmOLaBNJlIVGBLAFdHW0N.jpg',
  'tumbbad': 'https://image.tmdb.org/t/p/w500/wFVYbPVFgSFeaDiIKp68j5gQrOd.jpg',
  'udaan': 'https://image.tmdb.org/t/p/w500/oe4YKneMHPg98wB9eZpWJBK9xSW.jpg',
  'kahaani': 'https://image.tmdb.org/t/p/w500/9AoUqsJaTGX84yz1hJVV8bQRzpB.jpg',
  'dil-chahta-hai': 'https://image.tmdb.org/t/p/w500/u6m49QBdqEiJabsxuNEgLEPMzPG.jpg',
  'bajrangi-bhaijaan': 'https://image.tmdb.org/t/p/w500/qmZTJbYMPGFVcgfgfqKP1sE0Rqg.jpg',
  'masaan': 'https://image.tmdb.org/t/p/w500/71fJrLgjzvQSTX0Y0ZnPX5GNAZM.jpg',
  'aligarh': 'https://image.tmdb.org/t/p/w500/1uRYr0TBYRVXtjPb0NWQfJjxZyZ.jpg',
  'chhichhore': 'https://image.tmdb.org/t/p/w500/fkCHqk4CznMGYkdRj4RWG3TqLOZ.jpg',
  'URI': 'https://image.tmdb.org/t/p/w500/yWr0l9WmXgJO8nxjgMdEgQkvDKw.jpg',
  'stree': 'https://image.tmdb.org/t/p/w500/7NisDKjH5FJCFzVA5NxWTT5vXP6.jpg',
  'lunchbox': 'https://image.tmdb.org/t/p/w500/hVyQNmEyVOqFLGbVb0qUwPNdejf.jpg',
  'piku': 'https://image.tmdb.org/t/p/w500/bZARrFKp8Iz0qA3EcPfzHoQmHKN.jpg',
  'shahid': 'https://image.tmdb.org/t/p/w500/vdGStJWxwfMg3RNZJnLnQbkbCl8.jpg',
};

// Fallback poster for movies not in the mapping
export const getDefaultPoster = (genre: string[]) => {
  const genrePosters: Record<string, string> = {
    'Action': 'https://images.unsplash.com/photo-1565690381759-4cf96a7a4a05?w=400&h=600&fit=crop',
    'Drama': 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
    'Comedy': 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=400&h=600&fit=crop',
    'Sci-Fi': 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=400&h=600&fit=crop',
    'Romance': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop',
    'Thriller': 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
    'Horror': 'https://images.unsplash.com/photo-1571847019282-3311e3df4d8e?w=400&h=600&fit=crop',
    'Animation': 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=400&h=600&fit=crop',
  };
  
  // Return poster based on first genre
  const firstGenre = genre[0];
  return genrePosters[firstGenre] || 'https://images.unsplash.com/photo-1659497379075-a807be116f74?w=400&h=600&fit=crop';
};

export function getMoviePoster(movieId: string, genre: string[]): string {
  return posterMapping[movieId] || getDefaultPoster(genre);
}